apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |
      apiVersion: apps/v1
      kind: App
      metadata:
        name: apps
      spec:
        template:
          spec:
            imagePullSecrets:
              - name: github-token
    target:
      group: apps
      version: v1