apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: beta

commonLabels:
  app: clash
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: clash

resources:
- deployment.yaml
- service.yaml

