apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: appropriate/curl
      command:
        - sleep
      args:
        - infinity
    - name: docker
      image: ghcr.io/redstone1994/docker:latest
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
    - name: proxy
      image: ghcr.io/redstone1994/clash:5dcdefa
      volumeMounts:
        - mountPath: /home/clash/.config/clash/config.yaml
          name: conf
          subPath: config.yaml
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
        privileged: true
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: conf
      secret:
        secretName: clash-config