apiVersion: v1
kind: Secret
metadata:
  name: clash-conf
  namespace: devops
type: Opaque
stringData:
  config.yaml: |
    # mixed-port 端口将同时支持 SOCKS5/HTTP
    mixed-port: 7890
    tproxy-port: 7893
    
    # 绑定到所有接口
    bind-address: '*'
    
    # 允许局域网的连接
    allow-lan: true
    
    # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
    mode: Rule
    
    # 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
    # 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
    log-level: info
    # Clash 的 RESTful API
    external-controller: 0.0.0.0:9090
      # experimental:
    # ignore-resolve-fail: true
    # RESTful API 的口令
    secret: ''
    
    # 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
    # 参数应填写配置目录的相对路径或绝对路径。
    # external-ui: './dashboard'
    
    dns:
      enable: true # set true to enable dns (default is false)
      ipv6: false # default is false
      listen: 0.0.0.0:1053 #
      enhanced-mode: fake-ip # or fake-ip  redir-host
      fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
      nameserver:
        - 114.114.114.114 # default value
        - 8.8.8.8 # default value
        - tls://dns.rubyfish.cn:853 # DNS over TLS
        - https://1.1.1.1/dns-query # DNS over HTTPS
        - dhcp://en0 # dns from dhcp
        # fallback:
    #interface-name: eth0
    #是否开启tun
    #tun:
    #  enable: true
    #  stack: system
    #  dns-hijack:
    #    - 8.8.8.8:53
    #    - tcp://8.8.8.8:53
    #  auto-route: true # auto set global route
    #  auto-detect-interface: true
    
    proxies:
      - name: "vmess"
        type: vmess
        server: 
        port: 
        uuid: 
        alterId: 0
        cipher: auto
        # udp: true
        tls: true
        skip-cert-verify: true
        servername:
        network: ws
        ws-opts:
          path: /
    proxy-groups:
      - name: auto
        type: select
        # disable-udp: true
        proxies:
          - vmess
    
    rules:
      - DOMAIN-SUFFIX,google.com,auto
      - DOMAIN-KEYWORD,google,auto
      - DOMAIN,google.com,auto
      - DOMAIN-SUFFIX,ad.com,REJECT
      - SRC-IP-CIDR,192.168.1.201/32,DIRECT
      # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
      - IP-CIDR,127.0.0.0/8,DIRECT
      - GEOIP,CN,DIRECT
      - DST-PORT,80,DIRECT
      - SRC-PORT,7777,DIRECT
      # - RULE-SET,apple,REJECT # Premium only
      - SRC-IP-CIDR,10.0.24.16/22,DIRECT
      - SRC-IP-CIDR,10.96.0.0/16,DIRECT
      - IP-CIDR,10.96.0.0/16,DIRECT
      - IP-CIDR,10.0.24.16/22,DIRECT
      - IP-CIDR,10.0.0.0/8,DIRECT
      - SRC-IP-CIDR,10.0.0.0/8,DIRECT
      - DOMAIN-SUFFIX,tencentyun.com,DIRECT
      - DOMAIN-SUFFIX,local,DIRECT
      - DOMAIN-SUFFIX,svc,DIRECT
      - DOMAIN-SUFFIX,luadns.com,DIRECT
      - DOMAIN-SUFFIX,.tencentyun.com,DIRECT
      - MATCH,auto
