apiVersion: v1
kind: Service
metadata:
  name: clash-service
  namespace: devops
  labels:
    app: clash
spec:
  selector:
    app: clash
  ports:
    - name: http
      port: 7890
      protocol: TCP
      targetPort: 7890
    - name: tproxy
      port: 7893
      protocol: TCP
      targetPort: 7893
    - name: controller
      port: 9090
      protocol: TCP
      targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: clash-external
  namespace: devops
spec:
  type: ExternalName
  externalName: clash-service.devops.svc.cluster.local