apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clash-conf
  namespace: prod
spec:
  encryptedData:
    config.yaml: 
  template:
    metadata:
      creationTimestamp: null
      name: clash-conf
      namespace: default
    type: Opaque
