apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beta
namePrefix: beta-

commonLabels:
  app: aut-admin
  app.kubernetes.io/name: aut-admin
  app.kubernetes.io/managed-by: kustomize

components:
  - pull-secret.yaml

resources:
  - config.yaml
  - service.yaml
  - aut-admin.yaml