apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beta
namePrefix: beta-

commonLabels:
  app: aut-admin
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: aut-admin

components:
  - ../components/kustomization.yaml

resources:
  - config.yaml
  - service.yaml
  - aut-admin.yaml
images:
  - name: ghcr.io/redstone1994/aut-admin
    newTag: eda3f9c
