apiVersion: v1
kind: Service
metadata:
  name: aut-admin-service
  namespace: beta
  labels:
    app: aut-admin

spec:
  type: NodePort
  ports:
    - port: 8080
      name: tcp
      protocol: TCP
      nodePort: 30480
  selector:
    app: aut-admin