apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: beta
data:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials
  #1.auth = echo -n "username:token" | base64
  #2. echo -n  '{"auths":{"ghcr.io":{"auth":""}}}' | base64
  .dockerconfigjson: ad
type: kubernetes.io/dockerconfigjson

