apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: beta
data:
  #auth = echo -n "username:token" | base64
  #echo -n  '{"auths":{"ghcr.io":{"auth":""}}}' | base64
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJnaHBfcnlBOFMyN0NaOFoweDlXVXZFOHpaZTVaTHFEUFZpMmx5VTlkIn19fQ==
type: kubernetes.io/dockerconfigjson

