apiVersion: v1
kind: ConfigMap
metadata:
  namespace: beta
  name: redis-conf
  labels:
    app: redis
data:
  redis.conf: |
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass Lee123
    pidfile /data/redis-6379.pid


