apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: test
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.6-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 1000m
              memory: 1024m
          volumeMounts:
            - mountPath: /usr/local/redis/redis.conf
              name: redis-conf
              subPath: redis.conf
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-conf
          configMap:
            name: redis-conf
        - name: redis-data

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 1Gi

