apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: test
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.6-alpine
          command:
            - "sh"
            - "-c"
            - "redis-server /usr/local/etc/redis/redis.conf"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 100m
              memory: 1024m
          volumeMounts:
            - mountPath: /usr/local/etc/redis/redis.conf
              name: redis-conf
              subPath: redis.conf
            - mountPath: /data
              name: redis-data-pvc
      volumes:
        - name: redis-conf
          configMap:
            name: redis-conf


  volumeClaimTemplates:
    - metadata:
        name: redis-data-pvc
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 1Gi

