apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: beta
  labels:
    app: redis

spec:
  type: NodePort
  ports:
    - port: 6379
      name: tcp
      protocol: TCP
      nodePort: 30379
  selector:
    app: redis