name: build-iptables

on:
  push:
    paths:
      - 'iptables/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iptables

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: iptables/.
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
