name: build-jenkins

on:
  push:
    paths:
      - 'jenkins-lts-alpine/**'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd jenkins-lts-alpine && docker build . --file Dockerfile --tag jenkins-lts-alpine:$(date +%s)
